javac -d ./build -cp ./jars/itextpdf-5.5.13.3.jar:jars/pdfbox-app-2.0.27.jar:jars/commons-lang3-3.12.0.jar src/*.java
{
  echo "Jan Poonthong"
  echo "AI Engineer"
  echo "Koh Samui, Thailand"
  echo "janpoonthong628@gmail.com"
  echo "0987913490"
  echo "https://janpoonthong.github.io/portfolio"
  echo "I am a qualified and professional web developer with five years of experience in database administration and website design. Strong creative and analytical skills. Team player with an eye for detail."
  echo "jan_profile.jpg"
  echo "start"
  echo  "Really Great Company"
  echo  "Application Developer"
  echo "2016-2019"
  echo  "Database administration and website design Built the logic for a streamlined ad-serving platform that scaled Educational institutions and online classroom management"
  echo "start"
  echo  "Really Great Company"
  echo  "Web Content Manager"
  echo "2014-2016"
  echo  "Database administration and website design Built the logic for a streamlined ad-serving platform that scaled Educational institutions and online classroom management"
  echo "start"
  echo  "Really Great Company"
  echo  "Analysis Content"
  echo "2010-2014"
  echo  "Database administration and website design Built the logic for a streamlined ad-serving platform that scaled Educational institutions and online classroom management"
  echo "done"
  echo "start"
  echo "Web Design"
  echo "start"
  echo "Design Thinking"
  echo "start"
  echo "Wireframe Creation"
  echo "start"
  echo "Front End Coding"
  echo "start"
  echo "Problem-Solving"
  echo "start"
  echo "Computer Literacy"
  echo "start"
  echo "Project Management Tools"
  echo "start"
  echo "Strong Communication"
  echo "start"
  echo "Secondary school"
  echo "Really Great High School"
  echo "2010-2014"
  echo "start"
  echo "Bachelor of Technology"
  echo "Really Great University"
  echo "2014-2016"
} | java -cp ./build:./jars/itextpdf-5.5.13.3.jar:jars/pdfbox-app-2.0.27.jar:jars/commons-lang3-3.12.0.jar Main

open Jan_Poonthong_resume.pdf 

